apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mydep
  template:
    metadata:
      labels:
        app: mydep
    spec:
      containers:
      - name: mydep
        image: us.icr.io/sknsk8s/skfirstapp:v2
        ports:
        - containerPort: 8080
